scraper/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('web.urls', namespace='web')),
]

web/urls.py
from django.conf.urls import url

from .views import *


urlpatterns = [
    url(r'^science/$', ScienceItemListView.as_view(), name='science'),
    url(r'^technology/$', TechnologyItemListView.as_view(), name='technology'),
    url(r'^entertainment/$', EntertainmentItemListView.as_view(), name='entertainment'),
    url(r'^music/$', MusicItemListView.as_view(), name='music'),
    url(r'^$', HomeTemplateView.as_view(), name='home'),
]

web/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class BaseAbstractItem(models.Model):
    url = models.URLField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    image_url = models.URLField()
    description = models.TextField(blank=True, null=True)

    def __unicode__(self):
        try:
            return self.title
        except AttributeError:
            return self.url[:60]  # Truncate long urls

    class Meta:
        abstract = True


class EntertainmentItem(BaseAbstractItem):
    pass


class MusicItem(BaseAbstractItem):
    pass


class TechnologyItem(BaseAbstractItem):
    pass


class ScienceItem(BaseAbstractItem):
    title = models.CharField(max_length=255)

web/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic.list import ListView
from django.views.generic import TemplateView

from .models import ScienceItem, MusicItem, EntertainmentItem, TechnologyItem


class ScienceItemListView(ListView):
    model = ScienceItem
    paginate_by = 10


class TechnologyItemListView(ListView):
    model = TechnologyItem
    paginate_by = 10


class EntertainmentItemListView(ListView):
    model = EntertainmentItem
    paginate_by = 10


class MusicItemListView(ListView):
    model = MusicItem
    paginate_by = 10


class HomeTemplateView(TemplateView):
    template_name = 'web/home.html'

    def get_context_data(self, **kwargs):
        c = super(HomeTemplateView, self).get_context_data(**kwargs)

        c['science_count'] = ScienceItem.objects.count()
        c['music_count'] = MusicItem.objects.count()
        c['entertainment_count'] = EntertainmentItem.objects.count()
        c['technology_count'] = TechnologyItem.objects.count()

        return c

scraper/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Import materialize.css-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Dashboard | {% block title %}{% endblock %}</title>
</head>

<body>
<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<ul id="navDrop" class="dropdown-content">
  <li><a href="{% url 'web:science' %}">Science</a></li>
  <li><a href="{% url 'web:technology' %}">Technology</a></li>
  <li><a href="{% url 'web:entertainment' %}">Entertainment</a></li>
  <li><a href="{% url 'web:music' %}">Music</a></li>
</ul>
<nav class="blue darken-2">
  <div class="nav-wrapper">
    <a href="{% url 'web:home' %}" style="font-size: 20px; margin-left: 30px;">Scraping Dashboard</a>
    <ul class="right hide-on-med-and-down">
      <li><a href="/admin/">Admin</a></li>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-button" href="#!" data-activates="navDrop" data-beloworigin="true">Categories<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>
<div class="container">
  {% block content %}{% endblock %}
</div>
</body>
</html>

web/templates/web/entertainmentitem_list.html
{% extends 'base.html' %}
{% block title %}Entertainment{% endblock %}
{% block content %}
  <h1 class="grey-text text-darken-2">Entertainment Items</h1>
  {% include 'web/object_list_partial.html' with object_list=object_list %}
{% endblock %}

web/templates/web/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
  <div class="row section">
    <div class="col l3 s6">
      <div class="z-depth-1 center" style="padding: 30px;">
        <h5>Entertainment</h5>
        <h2>{{ entertainment_count }}</h2>
        <a href="{% url 'web:entertainment' %}">View</a>
      </div>
    </div>
    <div class="col l3 s6">
      <div class="z-depth-1 center" style="padding: 30px;">
        <h5>Science</h5>
        <h2>{{ science_count }}</h2>
        <a href="{% url 'web:science' %}">View</a>
      </div>
    </div>
    <div class="col l3 s6">
      <div class="z-depth-1 center" style="padding: 30px;">
        <h5>Music</h5>
        <h2>{{ music_count }}</h2>
        <a href="{% url 'web:music' %}">View</a>
      </div>
    </div>
    <div class="col l3 s6">
      <div class="z-depth-1 center" style="padding: 30px;">
        <h5>Technology</h5>
        <h2>{{ technology_count }}</h2>
        <a href="{% url 'web:technology' %}">View</a>
      </div>
    </div>
  </div>
{% endblock %}

web/templates/web/musicitem_list.html
{% extends 'base.html' %}
{% block title %}Music{% endblock %}
{% block content %}
  <h1 class="grey-text text-darken-2">Music Items</h1>
  {% include 'web/object_list_partial.html' with object_list=object_list %}
{% endblock %}

web/templates/web/object_list_partial.html
<div class="row">
  {% for item in object_list %}
    <div class="col s12 l6">
      <div class="card" {% if item.image_url %}style="min-height: 550px;"{% endif %}>
        {% if item.image_url %}
          <div class="card-image">
            <img src="{{ item.image_url }}">
            <span class="card-title">{{ item.created_at }}</span>
          </div>
        {% endif %}
        <div class="card-content">
          {% if not item.image_url %}<span class="card-title">{{ item.created_at }}</span>{% endif %}
          {% if item.description %}<p>{{ item.description }}</p>{% endif %}
        </div>
        <div class="card-action">
          <a href="{{ item.url }}">View Site</a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
<div class="row center">
  {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="wave-effect"><a href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
      {% else %}
        <li class="disabled"><i class="material-icons">chevron_left</i></li>
      {% endif %}

      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="active waves-effect"><a href="#!">{{ i }} </a></li>
        {% else %}
          <li class="waves-effect"><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="wave-effect"><a href="?page={{ page_obj.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
      {% else %}
        <li class="disabled"><i class="material-icons">chevron_right</i></li>
      {% endif %}
    </ul>
  {% endif %}
</div>

web/templates/web/scienceitem_list.html
{% extends 'base.html' %}
{% block title %}Science{% endblock %}
{% block content %}
<h1 class="grey-text text-darken-2">Science Items</h1>
  {% include 'web/object_list_partial.html' with object_list=object_list %}
{% endblock %}

web/templates/web/technologyitem_list.html
{% extends 'base.html' %}
{% block title %}Technology{% endblock %}
{% block content %}
  <h1 class="grey-text text-darken-2">Technology Items</h1>
  {% include 'web/object_list_partial.html' with object_list=object_list %}
{% endblock %}